### ISSUE TITLE
ReferenceError: URL Is not defined

### ISSUE THREAD

**Issue by karasaj** [everettsouthwick/amazon-auto-reload#15]
Running off of master on:

Raspberry Pi 3B+
Ubuntu Mate 18.10 64-bit
Chromium v74.0.3729.169
Chromedriver v74.0.3729.169

Packages installed with node v8.10.0 and npm version 3.5.2

Seeing the following error when running "npm start":

(node:13719) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at new Site (.../repos/amazon-auto-reload/dist/lib/site.js:6:32)
    at new Amazon (.../repos/amazon-auto-reload/dist/sites/amazon.js:10:9)
    at start (.../repos/amazon-auto-reload/dist/index.js:79:20)
    at Object.<anonymous> (.../repos/amazon-auto-reload/dist/index.js:235:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
(node:13719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am able to run on the Pi 3B+ using the old Python branch. I looked into dist/lib/site.js, and didn't see any obvious definition of StartingURL, but my node is very very rusty and I don't know if the definition would be floating around somewhere else.

**Comment by ab763** [comment]
Thank you. It appears that URL is in Node 10, and you're using Node 8. https://nodejs.org/api/url.html#url_the_whatwg_url_api

I may be able to get it working in Node 8, although apologies, is there a particular reason you're using Node 8 instead of 10? https://nodejs.org/en/download/

When Everett earlier released the JS version, he did specify Node v10.15.3 or newer, but as I haven't been testing across different versions I hadn't included a Node version requirement in the latest version.

Thank you.

**Comment by ab763** [comment]
(FYI StartingURL is fine - it's the code "... = new URL(..." that your Node is erroring on.)

**Comment by karasaj** [comment]
Only using Node 8 because it was the initial version that got picked up by The OS, I think. There shouldn't be any reason I can't uprev, let me try it. Could be worth adding Node>= v10 into the readme?

**Comment by ab763** [comment]
Yeah, the lack of a current Node version requirement is on me. I'm trying to decide whether the best next steps are for me to test some different Node versions, make it work in v8, or just throw up the requirement. :-)

Thanks.

**Comment by karasaj** [comment]
Updating to version 10.16.0 resolved it. I think it would be fine to just put a requirement for Node >= v10 on the README imo, it's very easy to upgrade Node with nvm. (You could throw in a link to that if you want to really be explicit)

**Comment by ab763** [comment]
Thanks. I did a little research and supporting Node.js v8 wasn't too bad. Well, at least getting it building and starting - I didn't extensively test on that Node.js version. I pushed the updated version to https://github.com/ab763/finance-transact
