### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 74

### ISSUE THREAD

**Issue by mcg88** [everettsouthwick/amazon-auto-reload#17]
Hello,

i'm getting this error when trying to launch the app.

```
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)
```

What is the easiest way to resolve?

**Comment by ab763** [comment]
Hmm, solely from looking at the code:
[package.json](https://github.com/everettsouthwick/amazon-auto-reload/blob/9de3c0ffd4bd8d0a17ba79cc6c9f91614da4e4ce/package.json#L31) specifically says `"chromedriver": "latest"`. However, the repository also includes package-lock.json, as [recommended](https://docs.npmjs.com/files/package-lock.json) - but perhaps it shouldn't be? Could see if a _fresh_ install after deleting package-lock.json resolves it?

**Comment by mcg88** [comment]
This resolved it.

**Comment by mcg88** [comment]
This issue is back `SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 77`
